---
# tasks file for rsyslog
- name: Copy file with owner and permissions
  copy:
    src: vagrant
    dest: /etc/sudoers.d/vagrant
    owner: root
    group: root
    mode: '0440'
- name: Appending the user 'vagrant'to the group 'wheel'
  user:
    name: vagrant
    groups: wheel
    append: yes
- name: vim
  yum:
    name: vim
    state: latest  
- name: install the firewall
  yum:
    name: firewalld
    state: latest    
- name: start the firewall
  service:
    name: firewalld 
    state: started
    enabled: true 
- name: firewalld permits 514/tcp
  firewalld:
    port: 514/tcp
    permanent: yes
    immediate: yes
    state: enabled
- name: Copy file with owner and permissions
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: '0644'    
- name: Make sure rsyslog is running
  systemd:
    state: restarted
    name: rsyslog     
